name:                polysemy-check
version:             0.1.0.0
github:              "polysemy-research/polysemy-check"
license:             BSD3
author:              "Sandy Maguire"
maintainer:          "sandy@sandymaguire.me"
copyright:           "Sandy Maguire"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/polysemy-research/polysemy-check#readme>

default-extensions:
- AllowAmbiguousTypes
- ConstraintKinds
- DataKinds
- FlexibleContexts
- FlexibleInstances
- GADTs
- LambdaCase
- MultiParamTypeClasses
- PolyKinds
- RankNTypes
- ScopedTypeVariables
- StandaloneDeriving
- TemplateHaskell
- TypeApplications
- TypeFamilies
- TypeOperators
- UndecidableInstances

ghc-options:
- -Wall

dependencies:
- base >= 4.7 && < 5
- polysemy
- containers
- QuickCheck
- kind-generics
- kind-generics-th

library:
  source-dirs: src
