name:                polysemy-check
version:             0.9.0.0
github:              "polysemy-research/polysemy-check"
license:             BSD3
author:              "Sandy Maguire"
maintainer:          "sandy@sandymaguire.me"
copyright:           "Sandy Maguire"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            QuickCheck for Polysemy
category:            Polysemy

description:         Please see the README on GitHub at <https://github.com/polysemy-research/polysemy-check#readme>

default-extensions:
- AllowAmbiguousTypes
- ConstraintKinds
- DataKinds
- FlexibleContexts
- FlexibleInstances
- GADTs
- LambdaCase
- MultiParamTypeClasses
- PolyKinds
- RankNTypes
- ScopedTypeVariables
- StandaloneDeriving
- TemplateHaskell
- TypeApplications
- TypeFamilies
- TypeOperators
- UndecidableInstances

ghc-options:
- -Wall

dependencies:
- base >= 4.7 && < 5
- polysemy
- containers
- QuickCheck
- kind-generics >= 0.4.1.2
- kind-generics-th

library:
  source-dirs: src

tests:
  test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    build-tools:
    - hspec-discover >= 2.0
    dependencies:
    - polysemy-check
    - polysemy-plugin
    - hspec
